import type { DefinicionSimbolo } from "@/types/symbol";

/**
 * Piezas direccionales para la herramienta "Camino" (editor/tools/caminoAutoTile.ts)
 * — recta/curva/T/cruce/terminal, más las piezas extra de esta carpeta para
 * arrastre manual. Los ids de las piezas nucleo deben coincidir exactamente
 * con lo que arma calcularPiezasCamino.
 */
export const CALLES_VEHICULARES: DefinicionSimbolo[] = [
  { id: "calle-vehicular-recta-norte-sur", nombre: "Recta norte-sur", categoria: "calles-vehiculares", icono: "/symbols/calles internas vehiculares del predio/01_recta_norte_sur.png", prefijo: "CVP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "calle-vehicular-recta-este-oeste", nombre: "Recta este-oeste", categoria: "calles-vehiculares", icono: "/symbols/calles internas vehiculares del predio/02_recta_este_oeste.png", prefijo: "CVP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "calle-vehicular-curva-norte-este", nombre: "Curva norte-este", categoria: "calles-vehiculares", icono: "/symbols/calles internas vehiculares del predio/03_curva_norte_este.png", prefijo: "CVP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "calle-vehicular-curva-este-sur", nombre: "Curva este-sur", categoria: "calles-vehiculares", icono: "/symbols/calles internas vehiculares del predio/04_curva_este_sur.png", prefijo: "CVP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "calle-vehicular-curva-sur-oeste", nombre: "Curva sur-oeste", categoria: "calles-vehiculares", icono: "/symbols/calles internas vehiculares del predio/05_curva_sur_oeste.png", prefijo: "CVP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "calle-vehicular-curva-oeste-norte", nombre: "Curva oeste-norte", categoria: "calles-vehiculares", icono: "/symbols/calles internas vehiculares del predio/06_curva_oeste_norte.png", prefijo: "CVP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "calle-vehicular-t-sin-norte", nombre: "Empalme en T (sin norte)", categoria: "calles-vehiculares", icono: "/symbols/calles internas vehiculares del predio/07_t_sin_norte.png", prefijo: "CVP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "calle-vehicular-t-sin-este", nombre: "Empalme en T (sin este)", categoria: "calles-vehiculares", icono: "/symbols/calles internas vehiculares del predio/08_t_sin_este.png", prefijo: "CVP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "calle-vehicular-t-sin-sur", nombre: "Empalme en T (sin sur)", categoria: "calles-vehiculares", icono: "/symbols/calles internas vehiculares del predio/09_t_sin_sur.png", prefijo: "CVP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "calle-vehicular-t-sin-oeste", nombre: "Empalme en T (sin oeste)", categoria: "calles-vehiculares", icono: "/symbols/calles internas vehiculares del predio/10_t_sin_oeste.png", prefijo: "CVP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "calle-vehicular-cruce", nombre: "Cruce de cuatro vías", categoria: "calles-vehiculares", icono: "/symbols/calles internas vehiculares del predio/11_cruce_cuatro_vias.png", prefijo: "CVP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "calle-vehicular-terminal-norte", nombre: "Final de camino (norte)", categoria: "calles-vehiculares", icono: "/symbols/calles internas vehiculares del predio/12_terminal_norte.png", prefijo: "CVP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "calle-vehicular-terminal-sur", nombre: "Final de camino (sur)", categoria: "calles-vehiculares", icono: "/symbols/calles internas vehiculares del predio/13_terminal_sur.png", prefijo: "CVP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "calle-vehicular-extra-rotonda", nombre: "Rotonda", categoria: "calles-vehiculares", icono: "/symbols/calles internas vehiculares del predio/12_rotonda.png", prefijo: "CVP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "calle-vehicular-extra-acceso-vehicular", nombre: "Acceso vehicular", categoria: "calles-vehiculares", icono: "/symbols/calles internas vehiculares del predio/13_acceso_vehicular.png", prefijo: "CVP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "calle-vehicular-extra-cruce-peatonal-en-calle-vehicular", nombre: "Cruce peatonal en calle vehicular", categoria: "calles-vehiculares", icono: "/symbols/calles internas vehiculares del predio/14_cruce_peatonal.png", prefijo: "CVP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
];
