import type { DefinicionSimbolo } from "@/types/symbol";

/**
 * Piezas direccionales para la herramienta "Camino" (editor/tools/caminoAutoTile.ts)
 * — recta/curva/T/cruce/terminal, más las piezas extra de esta carpeta para
 * arrastre manual. Los ids de las piezas nucleo deben coincidir exactamente
 * con lo que arma calcularPiezasCamino.
 */
export const CAMINOS_PAVIMENTADOS: DefinicionSimbolo[] = [
  { id: "camino-pavimentado-recta-norte-sur", nombre: "Recta norte-sur", categoria: "caminos-pavimentados", icono: "/symbols/Caminos peatonales pavimentados/01_recta_norte_sur.png", prefijo: "CPP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "camino-pavimentado-recta-este-oeste", nombre: "Recta este-oeste", categoria: "caminos-pavimentados", icono: "/symbols/Caminos peatonales pavimentados/02_recta_este_oeste.png", prefijo: "CPP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "camino-pavimentado-curva-norte-este", nombre: "Curva norte-este", categoria: "caminos-pavimentados", icono: "/symbols/Caminos peatonales pavimentados/03_curva_norte_este.png", prefijo: "CPP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "camino-pavimentado-curva-este-sur", nombre: "Curva este-sur", categoria: "caminos-pavimentados", icono: "/symbols/Caminos peatonales pavimentados/04_curva_este_sur.png", prefijo: "CPP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "camino-pavimentado-curva-sur-oeste", nombre: "Curva sur-oeste", categoria: "caminos-pavimentados", icono: "/symbols/Caminos peatonales pavimentados/05_curva_sur_oeste.png", prefijo: "CPP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "camino-pavimentado-curva-oeste-norte", nombre: "Curva oeste-norte", categoria: "caminos-pavimentados", icono: "/symbols/Caminos peatonales pavimentados/06_curva_oeste_norte.png", prefijo: "CPP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "camino-pavimentado-t-sin-norte", nombre: "Empalme en T (sin norte)", categoria: "caminos-pavimentados", icono: "/symbols/Caminos peatonales pavimentados/07_t_sin_norte.png", prefijo: "CPP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "camino-pavimentado-t-sin-este", nombre: "Empalme en T (sin este)", categoria: "caminos-pavimentados", icono: "/symbols/Caminos peatonales pavimentados/08_t_sin_este.png", prefijo: "CPP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "camino-pavimentado-t-sin-sur", nombre: "Empalme en T (sin sur)", categoria: "caminos-pavimentados", icono: "/symbols/Caminos peatonales pavimentados/09_t_sin_sur.png", prefijo: "CPP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "camino-pavimentado-t-sin-oeste", nombre: "Empalme en T (sin oeste)", categoria: "caminos-pavimentados", icono: "/symbols/Caminos peatonales pavimentados/10_t_sin_oeste.png", prefijo: "CPP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "camino-pavimentado-cruce", nombre: "Cruce de cuatro vías", categoria: "caminos-pavimentados", icono: "/symbols/Caminos peatonales pavimentados/11_cruce_cuatro_vias.png", prefijo: "CPP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "camino-pavimentado-terminal-norte", nombre: "Final de camino (norte)", categoria: "caminos-pavimentados", icono: "/symbols/Caminos peatonales pavimentados/12_terminal_norte.png", prefijo: "CPP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "camino-pavimentado-terminal-sur", nombre: "Final de camino (sur)", categoria: "caminos-pavimentados", icono: "/symbols/Caminos peatonales pavimentados/13_terminal_sur.png", prefijo: "CPP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: false, estiloIcono: "isometrico" },
  { id: "camino-pavimentado-extra-cruce-peatonal-pavimentado", nombre: "Cruce peatonal pavimentado", categoria: "caminos-pavimentados", icono: "/symbols/Caminos peatonales pavimentados/14_cruce_peatonal.png", prefijo: "CPP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "camino-pavimentado-extra-plaza-circular-conectable", nombre: "Plaza circular conectable", categoria: "caminos-pavimentados", icono: "/symbols/Caminos peatonales pavimentados/05_plaza_circular_conectable.png", prefijo: "CPP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "camino-pavimentado-extra-estacionamiento-accesible-camino", nombre: "Estacionamiento accesible (camino)", categoria: "caminos-pavimentados", icono: "/symbols/Caminos peatonales pavimentados/06_estacionamiento_accesible.png", prefijo: "CPP", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
];
