import type { DefinicionSimbolo } from "@/types/symbol";

export const ELECTRICIDAD: DefinicionSimbolo[] = [
  { id: "generador", nombre: "Generador eléctrico", categoria: "electricidad", icono: "/symbols/electricidad/generador.svg", prefijo: "GE", defaultWidth: 2, defaultHeight: 1.2, unit: "m", rotatable: true, resizable: false },
  { id: "toma-corriente", nombre: "Toma de corriente", categoria: "electricidad", icono: "/symbols/electricidad/toma.svg", prefijo: "TC", defaultWidth: 0.3, defaultHeight: 0.3, unit: "m", rotatable: false, resizable: false },
  { id: "tablero-electrico", nombre: "Tablero eléctrico", categoria: "electricidad", icono: "/symbols/electricidad/tablero.svg", prefijo: "TE", defaultWidth: 0.6, defaultHeight: 0.4, unit: "m", rotatable: true, resizable: false },

  // Colección "Iluminación, energía y servicios técnicos" — parte eléctrica
  // e iluminación isométrica, se suman a los SVG planos de arriba.
  { id: "iso-torre-iluminacion-portatil", nombre: "Torre de iluminación portátil", categoria: "electricidad", icono: "/symbols/Iluminación, energía y servicios técnicos/01_torre_iluminacion_portatil.png", prefijo: "IE", defaultWidth: 2, defaultHeight: 2, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-farola-doble-led", nombre: "Farola doble LED", categoria: "electricidad", icono: "/symbols/Iluminación, energía y servicios técnicos/02_farola_doble_led.png", prefijo: "IE", defaultWidth: 1, defaultHeight: 1, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-farola-peatonal-negra", nombre: "Farola peatonal negra", categoria: "electricidad", icono: "/symbols/Iluminación, energía y servicios técnicos/02_farola_peatonal_negra.png", prefijo: "IE", defaultWidth: 0.8, defaultHeight: 0.8, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-generador-electrico-portatil", nombre: "Generador eléctrico portátil", categoria: "electricidad", icono: "/symbols/Iluminación, energía y servicios técnicos/04_generador_electrico_portatil.png", prefijo: "IE", defaultWidth: 1.5, defaultHeight: 1, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-tablero-electrico-exterior", nombre: "Tablero eléctrico exterior", categoria: "electricidad", icono: "/symbols/Iluminación, energía y servicios técnicos/05_tablero_electrico_exterior.png", prefijo: "IE", defaultWidth: 0.8, defaultHeight: 0.5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-protector-cables", nombre: "Protector de cables", categoria: "electricidad", icono: "/symbols/Iluminación, energía y servicios técnicos/06_protector_de_cables.png", prefijo: "IE", defaultWidth: 1.5, defaultHeight: 0.4, unit: "m", rotatable: true, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-transformador-electrico", nombre: "Transformador eléctrico", categoria: "electricidad", icono: "/symbols/Iluminación, energía y servicios técnicos/07_transformador_electrico.png", prefijo: "IE", defaultWidth: 1.5, defaultHeight: 1.2, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-farola-solar", nombre: "Farola solar", categoria: "electricidad", icono: "/symbols/Iluminación, energía y servicios técnicos/08_farola_solar.png", prefijo: "IE", defaultWidth: 1, defaultHeight: 1, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-torre-megafonia", nombre: "Torre de megafonía", categoria: "electricidad", icono: "/symbols/Iluminación, energía y servicios técnicos/14_torre_megafonia.png", prefijo: "IE", defaultWidth: 1.5, defaultHeight: 1.5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-modulo-tecnico-servicios", nombre: "Módulo técnico de servicios", categoria: "electricidad", icono: "/symbols/Iluminación, energía y servicios técnicos/15_modulo_tecnico_servicios.png", prefijo: "IE", defaultWidth: 2, defaultHeight: 1.5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
];
