import type { DefinicionSimbolo } from "@/types/symbol";

export const EMERGENCIAS: DefinicionSimbolo[] = [
  { id: "atencion-medica", nombre: "Puesto de atención médica", categoria: "emergencias", icono: "/symbols/emergencias/primeros-auxilios.svg", prefijo: "PM", defaultWidth: 3, defaultHeight: 3, unit: "m", rotatable: true, resizable: true },
  { id: "ambulancia", nombre: "Ambulancia", categoria: "emergencias", icono: "/symbols/emergencias/ambulancia.svg", prefijo: "AM", defaultWidth: 2.5, defaultHeight: 5, unit: "m", rotatable: true, resizable: false },
  { id: "bomberos", nombre: "Bomberos", categoria: "emergencias", icono: "/symbols/emergencias/bomberos.svg", prefijo: "BO", defaultWidth: 2, defaultHeight: 2, unit: "m", rotatable: false, resizable: false },
  { id: "matafuego", nombre: "Extintor", categoria: "emergencias", icono: "/symbols/emergencias/extintor.svg", prefijo: "MT", defaultWidth: 0.5, defaultHeight: 0.5, unit: "m", rotatable: false, resizable: false },
  { id: "hidrante", nombre: "Hidrante", categoria: "emergencias", icono: "/symbols/emergencias/hidrante.svg", prefijo: "HI", defaultWidth: 0.5, defaultHeight: 0.5, unit: "m", rotatable: false, resizable: false },
  { id: "punto-evacuacion", nombre: "Punto de evacuación", categoria: "emergencias", icono: "/symbols/emergencias/punto-encuentro.svg", prefijo: "PV", defaultWidth: 2, defaultHeight: 2, unit: "m", rotatable: false, resizable: false },
  { id: "punto-encuentro", nombre: "Punto de encuentro", categoria: "emergencias", icono: "/symbols/emergencias/punto-encuentro.svg", prefijo: "PE", defaultWidth: 2, defaultHeight: 2, unit: "m", rotatable: false, resizable: false },
  { id: "ruta-evacuacion", nombre: "Ruta de evacuación", categoria: "emergencias", icono: "/symbols/emergencias/ruta-evacuacion.svg", prefijo: "RE", defaultWidth: 3, defaultHeight: 0.3, unit: "m", rotatable: true, resizable: true },
  { id: "salida-emergencia-sim", nombre: "Salida de emergencia", categoria: "emergencias", icono: "/symbols/accesos/salida-emergencia.svg", prefijo: "SE", defaultWidth: 1.5, defaultHeight: 0.6, unit: "m", rotatable: true, resizable: true },
  { id: "puesto-seguridad", nombre: "Puesto de seguridad", categoria: "emergencias", icono: "/symbols/emergencias/puesto-seguridad.svg", prefijo: "PS", defaultWidth: 1.5, defaultHeight: 1.5, unit: "m", rotatable: true, resizable: true },
  { id: "camara-seguridad", nombre: "Cámara de seguridad", categoria: "emergencias", icono: "/symbols/emergencias/camara.svg", prefijo: "CM", defaultWidth: 0.4, defaultHeight: 0.4, unit: "m", rotatable: true, resizable: false },
  { id: "iluminacion-emergencia", nombre: "Iluminación de emergencia", categoria: "emergencias", icono: "/symbols/emergencias/iluminacion.svg", prefijo: "IE", defaultWidth: 0.4, defaultHeight: 0.4, unit: "m", rotatable: false, resizable: false },

  // Colección "Iluminación, energía y servicios técnicos" — señalización y
  // equipamiento de emergencia isométrico, se suma a los SVG planos de arriba.
  { id: "iso-senal-salida-emergencia", nombre: "Señal de salida de emergencia", categoria: "emergencias", icono: "/symbols/Iluminación, energía y servicios técnicos/04_senal_salida_emergencia.png", prefijo: "EG", defaultWidth: 0.6, defaultHeight: 0.6, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-porton-salida-emergencia", nombre: "Portón de salida de emergencia", categoria: "emergencias", icono: "/symbols/Iluminación, energía y servicios técnicos/05_porton_salida_emergencia.png", prefijo: "EG", defaultWidth: 3, defaultHeight: 0.6, unit: "m", rotatable: true, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-primeros-auxilios", nombre: "Primeros auxilios", categoria: "emergencias", icono: "/symbols/Iluminación, energía y servicios técnicos/09_primeros_auxilios.png", prefijo: "EG", defaultWidth: 0.6, defaultHeight: 0.6, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-salida-emergencia", nombre: "Salida de emergencia", categoria: "emergencias", icono: "/symbols/Iluminación, energía y servicios técnicos/10_salida_emergencia.png", prefijo: "EG", defaultWidth: 0.6, defaultHeight: 0.6, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-punto-encuentro", nombre: "Punto de encuentro", categoria: "emergencias", icono: "/symbols/Iluminación, energía y servicios técnicos/11_punto_encuentro.png", prefijo: "EG", defaultWidth: 0.8, defaultHeight: 0.8, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-hidrante-contra-incendios", nombre: "Hidrante contra incendios", categoria: "emergencias", icono: "/symbols/Iluminación, energía y servicios técnicos/12_hidrante_contra_incendios.png", prefijo: "EG", defaultWidth: 0.5, defaultHeight: 0.5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-poste-camaras-cctv", nombre: "Poste de cámaras CCTV", categoria: "emergencias", icono: "/symbols/Iluminación, energía y servicios técnicos/13_poste_camaras_cctv.png", prefijo: "EG", defaultWidth: 0.6, defaultHeight: 0.6, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
];
