import type { DefinicionSimbolo } from "@/types/symbol";

export const ESTACIONAMIENTO: DefinicionSimbolo[] = [
  { id: "estacionamiento-general", nombre: "Estacionamiento general", categoria: "estacionamiento", icono: "/symbols/estacionamiento/automovil.svg", prefijo: "EG", defaultWidth: 2.5, defaultHeight: 5, unit: "m", rotatable: true, resizable: true },
  { id: "estacionamiento-accesible", nombre: "Estacionamiento accesible", categoria: "estacionamiento", icono: "/symbols/estacionamiento/accesible.svg", prefijo: "EA", defaultWidth: 3.5, defaultHeight: 5, unit: "m", rotatable: true, resizable: true },
  { id: "estacionamiento-motos", nombre: "Estacionamiento de motos", categoria: "estacionamiento", icono: "/symbols/estacionamiento/motocicleta.svg", prefijo: "EM", defaultWidth: 1, defaultHeight: 2.2, unit: "m", rotatable: true, resizable: true },
  { id: "estacionamiento-bicicletas", nombre: "Estacionamiento de bicicletas", categoria: "estacionamiento", icono: "/symbols/estacionamiento/bicicleta.svg", prefijo: "EB", defaultWidth: 0.6, defaultHeight: 1.8, unit: "m", rotatable: true, resizable: true },
  { id: "estacionamiento-proveedores", nombre: "Estacionamiento de proveedores", categoria: "estacionamiento", icono: "/symbols/estacionamiento/automovil.svg", prefijo: "EP", defaultWidth: 3, defaultHeight: 8, unit: "m", rotatable: true, resizable: true },
  { id: "estacionamiento-ambulancias", nombre: "Estacionamiento de ambulancias", categoria: "estacionamiento", icono: "/symbols/emergencias/ambulancia.svg", prefijo: "EM2", defaultWidth: 3, defaultHeight: 6, unit: "m", rotatable: true, resizable: true },
  { id: "carga-descarga", nombre: "Zona de carga y descarga", categoria: "estacionamiento", icono: "/symbols/estacionamiento/carga-descarga.svg", prefijo: "CD", defaultWidth: 4, defaultHeight: 8, unit: "m", rotatable: true, resizable: true },

  // Colección "Estacionamientos modulares" — módulos de piso isométricos
  // (bahías, dársenas, accesos), se suman a los SVG planos de arriba, no los
  // reemplazan. La carpeta trae 3 piezas duplicadas bajo dos números
  // distintos (accesible, motos, bicicletas) — se usa la de menor número.
  { id: "modulo-estacionamiento-general-vacio", nombre: "Módulo de estacionamiento general vacío", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/01_estacionamiento_general_vacio.png", prefijo: "PM", defaultWidth: 5, defaultHeight: 2.5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "modulo-estacionamiento-perpendicular-vacio", nombre: "Módulo de estacionamiento perpendicular vacío", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/01_estacionamiento_perpendicular_vacio.png", prefijo: "PM", defaultWidth: 5, defaultHeight: 2.5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "modulo-estacionamiento-angular-vacio", nombre: "Módulo de estacionamiento angular vacío", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/02_estacionamiento_angular_vacio.png", prefijo: "PM", defaultWidth: 5, defaultHeight: 2.5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "modulo-estacionamiento-general-ocupado", nombre: "Módulo de estacionamiento general ocupado", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/02_estacionamiento_general_ocupado.png", prefijo: "PM", defaultWidth: 5, defaultHeight: 2.5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "modulo-estacionamiento-accesible", nombre: "Módulo de estacionamiento accesible", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/03_estacionamiento_accesible.png", prefijo: "PM", defaultWidth: 3.5, defaultHeight: 5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "modulo-estacionamiento-con-autos", nombre: "Módulo de estacionamiento con autos", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/03_estacionamiento_con_autos.png", prefijo: "PM", defaultWidth: 5, defaultHeight: 2.5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "modulo-estacionamiento-motos", nombre: "Módulo de estacionamiento de motos", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/04_estacionamiento_motos.png", prefijo: "PM", defaultWidth: 1, defaultHeight: 2.2, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "modulo-estacionamiento-bicicletas", nombre: "Módulo de estacionamiento de bicicletas", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/05_estacionamiento_bicicletas.png", prefijo: "PM", defaultWidth: 2, defaultHeight: 1.5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "modulo-estacionamiento-colectivos", nombre: "Módulo de estacionamiento de colectivos", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/06_estacionamiento_colectivos.png", prefijo: "PM", defaultWidth: 3.5, defaultHeight: 12, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "modulo-darsena-colectivo-minibus", nombre: "Dársena de colectivo/minibús", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/07_darsena_colectivo_minibus.png", prefijo: "PM", defaultWidth: 3.5, defaultHeight: 10, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "modulo-estacionamiento-minibuses", nombre: "Módulo de estacionamiento de minibuses", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/07_estacionamiento_minibuses.png", prefijo: "PM", defaultWidth: 3, defaultHeight: 8, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "modulo-darsena-vehiculos-servicio", nombre: "Dársena de vehículos de servicio", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/08_darsena_vehiculos_servicio.png", prefijo: "PM", defaultWidth: 3, defaultHeight: 6, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "modulo-estacionamiento-camionetas", nombre: "Módulo de estacionamiento de camionetas", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/08_estacionamiento_camionetas.png", prefijo: "PM", defaultWidth: 3, defaultHeight: 6, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "modulo-darsena-carga-descarga", nombre: "Dársena de carga y descarga", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/09_darsena_carga_descarga.png", prefijo: "PM", defaultWidth: 4, defaultHeight: 8, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "modulo-darsena-proveedores", nombre: "Dársena de proveedores", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/09_darsena_proveedores.png", prefijo: "PM", defaultWidth: 4, defaultHeight: 8, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "modulo-carga-descarga", nombre: "Módulo de carga y descarga", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/10_carga_descarga.png", prefijo: "PM", defaultWidth: 4, defaultHeight: 8, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "modulo-darsena-ascenso-descenso", nombre: "Dársena de ascenso y descenso", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/10_darsena_ascenso_descenso.png", prefijo: "PM", defaultWidth: 4, defaultHeight: 6, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "modulo-ascenso-descenso", nombre: "Módulo de ascenso y descenso", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/11_ascenso_descenso.png", prefijo: "PM", defaultWidth: 4, defaultHeight: 6, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "modulo-darsena-taxi-remis", nombre: "Dársena de taxi y remis", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/11_darsena_taxi_remis.png", prefijo: "PM", defaultWidth: 3, defaultHeight: 6, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "modulo-acceso-vehicular-controlado", nombre: "Acceso vehicular controlado", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/12_acceso_vehicular_controlado.png", prefijo: "PM", defaultWidth: 3, defaultHeight: 2, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "modulo-estacionamiento-emergencia", nombre: "Módulo de estacionamiento de emergencia", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/12_estacionamiento_emergencia.png", prefijo: "PM", defaultWidth: 3, defaultHeight: 6, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "modulo-acceso-con-barrera", nombre: "Acceso con barrera", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/13_acceso_con_barrera.png", prefijo: "PM", defaultWidth: 3, defaultHeight: 2, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "modulo-salida-vehicular-controlada", nombre: "Salida vehicular controlada", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/13_salida_vehicular_controlada.png", prefijo: "PM", defaultWidth: 3, defaultHeight: 2, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "modulo-area-maniobra-retorno", nombre: "Área de maniobra y retorno", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/14_area_maniobra_retorno.png", prefijo: "PM", defaultWidth: 6, defaultHeight: 6, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "modulo-salida-con-barrera", nombre: "Módulo de salida con barrera", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/14_salida_con_barrera.png", prefijo: "PM", defaultWidth: 3, defaultHeight: 2, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "modulo-isla-divisoria-vegetada", nombre: "Isla divisoria vegetada", categoria: "estacionamiento", icono: "/symbols/Estacionamientos modulares/15_isla_divisoria_vegetada.png", prefijo: "PM", defaultWidth: 2, defaultHeight: 1, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },

  // Colección "Vehículos y estacionamiento completada" — vehículos sueltos y
  // escenas de estacionamiento ya ocupado, para completar el plano.
  { id: "vehiculo-ambulancia", nombre: "Ambulancia", categoria: "estacionamiento", icono: "/symbols/Vehículos y estacionamiento completada/Ambulancia.png", prefijo: "VE", defaultWidth: 2.5, defaultHeight: 5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "vehiculo-autobomba", nombre: "Autobomba", categoria: "estacionamiento", icono: "/symbols/Vehículos y estacionamiento completada/Autobomba.png", prefijo: "VE", defaultWidth: 3, defaultHeight: 7, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "vehiculo-automoviles-colores", nombre: "Automóviles de distintos colores", categoria: "estacionamiento", icono: "/symbols/Vehículos y estacionamiento completada/Automóviles de distintos colores..png", prefijo: "VE", defaultWidth: 2.5, defaultHeight: 5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "vehiculo-bicicletas", nombre: "Bicicletas", categoria: "estacionamiento", icono: "/symbols/Vehículos y estacionamiento completada/Bicicletas..png", prefijo: "VE", defaultWidth: 1.5, defaultHeight: 1, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "vehiculo-camioneta-rural", nombre: "Camioneta rural", categoria: "estacionamiento", icono: "/symbols/Vehículos y estacionamiento completada/Camioneta rural.png", prefijo: "VE", defaultWidth: 2.5, defaultHeight: 5.5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "vehiculo-camion-carga", nombre: "Camión de carga", categoria: "estacionamiento", icono: "/symbols/Vehículos y estacionamiento completada/Camión de carga.png", prefijo: "VE", defaultWidth: 3, defaultHeight: 8, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "vehiculo-colectivo", nombre: "Colectivo", categoria: "estacionamiento", icono: "/symbols/Vehículos y estacionamiento completada/Colectivo.png", prefijo: "VE", defaultWidth: 3.5, defaultHeight: 12, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "vehiculo-darsena-proveedores", nombre: "Dársena para proveedores", categoria: "estacionamiento", icono: "/symbols/Vehículos y estacionamiento completada/Dársena para proveedores.png", prefijo: "VE", defaultWidth: 4, defaultHeight: 8, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "vehiculo-estacionamiento-motos", nombre: "Estacionamiento de motos (con vehículos)", categoria: "estacionamiento", icono: "/symbols/Vehículos y estacionamiento completada/Estacionamiento de motos.png", prefijo: "VE", defaultWidth: 3, defaultHeight: 2, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "vehiculo-estacionamiento-general-completo", nombre: "Estacionamiento general (con vehículos)", categoria: "estacionamiento", icono: "/symbols/Vehículos y estacionamiento completada/Estacionamiento general.png", prefijo: "VE", defaultWidth: 6, defaultHeight: 4, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "vehiculo-minibus", nombre: "Minibús", categoria: "estacionamiento", icono: "/symbols/Vehículos y estacionamiento completada/Minibús.png", prefijo: "VE", defaultWidth: 3, defaultHeight: 7, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "vehiculo-motocicletas", nombre: "Motocicletas", categoria: "estacionamiento", icono: "/symbols/Vehículos y estacionamiento completada/Motocicletas.png", prefijo: "VE", defaultWidth: 1.5, defaultHeight: 1, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "vehiculo-patrullero", nombre: "Patrullero", categoria: "estacionamiento", icono: "/symbols/Vehículos y estacionamiento completada/Patrullero.png", prefijo: "VE", defaultWidth: 2.5, defaultHeight: 5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "vehiculo-zona-ascenso-descenso", nombre: "Zona de ascenso y descenso", categoria: "estacionamiento", icono: "/symbols/Vehículos y estacionamiento completada/Zona de ascenso y descenso.png", prefijo: "VE", defaultWidth: 4, defaultHeight: 6, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "vehiculo-parada-colectivo", nombre: "Parada de colectivo", categoria: "estacionamiento", icono: "/symbols/Vehículos y estacionamiento completada/parada de colectivo.png", prefijo: "VE", defaultWidth: 2, defaultHeight: 1.5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },

  // Colección "autos" — sprites sueltos de autos de color para dar variedad
  // visual dentro de los módulos de estacionamiento.
  { id: "auto-azul", nombre: "Auto azul", categoria: "estacionamiento", icono: "/symbols/autos/azul.png", prefijo: "AU", defaultWidth: 2.2, defaultHeight: 4.5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "auto-blanco", nombre: "Auto blanco", categoria: "estacionamiento", icono: "/symbols/autos/blanco.png", prefijo: "AU", defaultWidth: 2.2, defaultHeight: 4.5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "auto-gris-oscuro", nombre: "Auto gris oscuro", categoria: "estacionamiento", icono: "/symbols/autos/gris-oscuro.png", prefijo: "AU", defaultWidth: 2.2, defaultHeight: 4.5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "auto-naranja", nombre: "Auto naranja", categoria: "estacionamiento", icono: "/symbols/autos/naranja.png", prefijo: "AU", defaultWidth: 2.2, defaultHeight: 4.5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "auto-naranja-variante", nombre: "Auto naranja (variante)", categoria: "estacionamiento", icono: "/symbols/autos/naranja_1.png", prefijo: "AU", defaultWidth: 2.2, defaultHeight: 4.5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "auto-rojo-1", nombre: "Auto rojo", categoria: "estacionamiento", icono: "/symbols/autos/rojo_1.png", prefijo: "AU", defaultWidth: 2.2, defaultHeight: 4.5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "auto-rojo-2", nombre: "Auto rojo (variante)", categoria: "estacionamiento", icono: "/symbols/autos/rojo_2.png", prefijo: "AU", defaultWidth: 2.2, defaultHeight: 4.5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "piso-estacionamiento-modular", nombre: "Piso de estacionamiento", categoria: "estacionamiento", icono: "/symbols/autos/piso_estacionamiento.png", prefijo: "AU", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
];
