import type { DefinicionSimbolo } from "@/types/symbol";

export const INFRAESTRUCTURA: DefinicionSimbolo[] = [
  { id: "stand", nombre: "Stand", categoria: "infraestructura", icono: "/symbols/stands/stand-simple.svg", prefijo: "ST", defaultWidth: 3, defaultHeight: 3, unit: "m", rotatable: true, resizable: true },
  { id: "carpa", nombre: "Carpa", categoria: "infraestructura", icono: "/symbols/stands/carpa.svg", prefijo: "CA", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: true, resizable: true },
  { id: "gazebo", nombre: "Gazebo", categoria: "infraestructura", icono: "/symbols/infraestructura/gazebo.svg", prefijo: "GZ", defaultWidth: 3, defaultHeight: 3, unit: "m", rotatable: true, resizable: true },
  { id: "escenario", nombre: "Escenario", categoria: "infraestructura", icono: "/symbols/stands/escenario.svg", prefijo: "ES", defaultWidth: 8, defaultHeight: 6, unit: "m", rotatable: true, resizable: true },
  { id: "deposito", nombre: "Depósito", categoria: "infraestructura", icono: "/symbols/infraestructura/deposito.svg", prefijo: "DE", defaultWidth: 3, defaultHeight: 3, unit: "m", rotatable: true, resizable: true },
  { id: "oficina", nombre: "Oficina", categoria: "infraestructura", icono: "/symbols/infraestructura/oficina.svg", prefijo: "OF", defaultWidth: 3, defaultHeight: 3, unit: "m", rotatable: true, resizable: true },
  { id: "casilla", nombre: "Casilla", categoria: "infraestructura", icono: "/symbols/infraestructura/casilla.svg", prefijo: "CS", defaultWidth: 2, defaultHeight: 2, unit: "m", rotatable: true, resizable: true },
  { id: "punto-informacion", nombre: "Punto de información", categoria: "infraestructura", icono: "/symbols/infraestructura/punto-informacion.svg", prefijo: "PI", defaultWidth: 1.5, defaultHeight: 1.5, unit: "m", rotatable: false, resizable: false },
  { id: "vestuario", nombre: "Vestuario", categoria: "infraestructura", icono: "/symbols/infraestructura/vestuario.svg", prefijo: "VE", defaultWidth: 3, defaultHeight: 3, unit: "m", rotatable: true, resizable: true },
  { id: "cabina-tecnica", nombre: "Cabina técnica", categoria: "infraestructura", icono: "/symbols/infraestructura/cabina-tecnica.svg", prefijo: "CT", defaultWidth: 2, defaultHeight: 2, unit: "m", rotatable: true, resizable: true },
  { id: "torre-sonido", nombre: "Torre de sonido", categoria: "infraestructura", icono: "/symbols/infraestructura/torre-sonido.svg", prefijo: "TS", defaultWidth: 1.5, defaultHeight: 1.5, unit: "m", rotatable: false, resizable: false },
  { id: "pantalla", nombre: "Pantalla", categoria: "infraestructura", icono: "/symbols/infraestructura/pantalla.svg", prefijo: "PA", defaultWidth: 4, defaultHeight: 0.5, unit: "m", rotatable: true, resizable: true },
  { id: "generador-electrico", nombre: "Generador eléctrico", categoria: "infraestructura", icono: "/symbols/electricidad/generador.svg", prefijo: "GE", defaultWidth: 2, defaultHeight: 1.2, unit: "m", rotatable: true, resizable: false },

  // Colección "esenarios" — edificios y escenarios isométricos grandes, se
  // suman a los SVG planos de arriba, no los reemplazan.
  { id: "iso-centro-cultural", nombre: "Centro cultural", categoria: "infraestructura", icono: "/symbols/esenarios/Centro cultural.png", prefijo: "EI", defaultWidth: 10, defaultHeight: 8, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-deposito-grande", nombre: "Depósito", categoria: "infraestructura", icono: "/symbols/esenarios/Depósito.png", prefijo: "EI", defaultWidth: 6, defaultHeight: 5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-enfermeria", nombre: "Enfermería y primeros auxilios", categoria: "infraestructura", icono: "/symbols/esenarios/Enfermería y primeros auxilios.png", prefijo: "EI", defaultWidth: 4, defaultHeight: 3, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-escenario-principal-cubierto", nombre: "Escenario principal cubierto", categoria: "infraestructura", icono: "/symbols/esenarios/Escenario principal cubierto..png", prefijo: "EI", defaultWidth: 12, defaultHeight: 8, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-escenario-secundario", nombre: "Escenario secundario", categoria: "infraestructura", icono: "/symbols/esenarios/Escenario secundario.png", prefijo: "EI", defaultWidth: 8, defaultHeight: 6, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-galpon-gastronomico", nombre: "Galpón gastronómico", categoria: "infraestructura", icono: "/symbols/esenarios/Galpón gastronómico.png", prefijo: "EI", defaultWidth: 8, defaultHeight: 6, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-oficina-organizacion", nombre: "Oficina de organización", categoria: "infraestructura", icono: "/symbols/esenarios/Oficina de organización.png", prefijo: "EI", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-puesto-bomberos", nombre: "Puesto de bomberos", categoria: "infraestructura", icono: "/symbols/esenarios/Puesto de bomberos.png", prefijo: "EI", defaultWidth: 4, defaultHeight: 4, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-puesto-informacion", nombre: "Puesto de información", categoria: "infraestructura", icono: "/symbols/esenarios/Puesto de información.png", prefijo: "EI", defaultWidth: 2.5, defaultHeight: 2.5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-puesto-seguridad", nombre: "Puesto de seguridad", categoria: "infraestructura", icono: "/symbols/esenarios/Puesto de seguridad.png", prefijo: "EI", defaultWidth: 2.5, defaultHeight: 2.5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-sala-prensa", nombre: "Sala de prensa", categoria: "infraestructura", icono: "/symbols/esenarios/Sala de prensa.png", prefijo: "EI", defaultWidth: 5, defaultHeight: 4, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-salon-conferencias", nombre: "Salón de conferencias", categoria: "infraestructura", icono: "/symbols/esenarios/Salón de conferencias.png", prefijo: "EI", defaultWidth: 8, defaultHeight: 6, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-sanitarios-edificio", nombre: "Sanitarios", categoria: "infraestructura", icono: "/symbols/esenarios/Sanitarios.png", prefijo: "EI", defaultWidth: 4, defaultHeight: 3, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-escenario-acustico", nombre: "Escenario acústico", categoria: "infraestructura", icono: "/symbols/esenarios/escenario_acustico.png", prefijo: "EI", defaultWidth: 8, defaultHeight: 6, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-escenario-circular-360", nombre: "Escenario circular 360°", categoria: "infraestructura", icono: "/symbols/esenarios/escenario_circular_360.png", prefijo: "EI", defaultWidth: 8, defaultHeight: 8, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-escenario-modular", nombre: "Escenario modular", categoria: "infraestructura", icono: "/symbols/esenarios/escenario_modular.png", prefijo: "EI", defaultWidth: 6, defaultHeight: 5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-escenario-principal", nombre: "Escenario principal", categoria: "infraestructura", icono: "/symbols/esenarios/escenario_principal.png", prefijo: "EI", defaultWidth: 12, defaultHeight: 8, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-escenario-secundario-b", nombre: "Escenario secundario (variante)", categoria: "infraestructura", icono: "/symbols/esenarios/escenario_secundario.png", prefijo: "EI", defaultWidth: 8, defaultHeight: 6, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
];
