import type { DefinicionSimbolo } from "@/types/symbol";

export const SENALIZACION: DefinicionSimbolo[] = [
  { id: "cartel-entrada", nombre: "Cartel de entrada", categoria: "senalizacion", icono: "/symbols/senalizacion/cartel.svg", prefijo: "CE", defaultWidth: 1, defaultHeight: 0.1, unit: "m", rotatable: true, resizable: true },
  { id: "cartel-salida", nombre: "Cartel de salida", categoria: "senalizacion", icono: "/symbols/senalizacion/cartel.svg", prefijo: "CS", defaultWidth: 1, defaultHeight: 0.1, unit: "m", rotatable: true, resizable: true },
  { id: "cartel-informacion", nombre: "Información", categoria: "senalizacion", icono: "/symbols/senalizacion/cartel.svg", prefijo: "CI", defaultWidth: 1, defaultHeight: 0.1, unit: "m", rotatable: true, resizable: true },
  { id: "prohibido-paso", nombre: "Prohibido el paso", categoria: "senalizacion", icono: "/symbols/senalizacion/prohibido.svg", prefijo: "PP", defaultWidth: 0.6, defaultHeight: 0.6, unit: "m", rotatable: false, resizable: false },
  { id: "cartel-banos", nombre: "Baños", categoria: "senalizacion", icono: "/symbols/senalizacion/cartel.svg", prefijo: "CB", defaultWidth: 0.8, defaultHeight: 0.1, unit: "m", rotatable: true, resizable: true },
  { id: "cartel-emergencias", nombre: "Emergencias", categoria: "senalizacion", icono: "/symbols/senalizacion/cartel.svg", prefijo: "CM", defaultWidth: 0.8, defaultHeight: 0.1, unit: "m", rotatable: true, resizable: true },
  { id: "cartel-encuentro", nombre: "Punto de encuentro", categoria: "senalizacion", icono: "/symbols/emergencias/punto-encuentro.svg", prefijo: "CP", defaultWidth: 0.8, defaultHeight: 0.8, unit: "m", rotatable: false, resizable: false },
  { id: "cartel-accesibilidad", nombre: "Accesibilidad", categoria: "senalizacion", icono: "/symbols/senalizacion/accesibilidad.svg", prefijo: "CA", defaultWidth: 0.6, defaultHeight: 0.6, unit: "m", rotatable: false, resizable: false },
  { id: "cartel-estacionamiento", nombre: "Estacionamiento", categoria: "senalizacion", icono: "/symbols/senalizacion/cartel.svg", prefijo: "CT", defaultWidth: 0.8, defaultHeight: 0.1, unit: "m", rotatable: true, resizable: true },
  { id: "numeracion-sector", nombre: "Numeración de sectores", categoria: "senalizacion", icono: "/symbols/senalizacion/numeracion.svg", prefijo: "NS", defaultWidth: 0.5, defaultHeight: 0.5, unit: "m", rotatable: false, resizable: false },
  { id: "flecha-norte", nombre: "Flecha norte", categoria: "senalizacion", icono: "/symbols/senalizacion/flecha-norte.svg", prefijo: "NO", defaultWidth: 1.5, defaultHeight: 2, unit: "m", rotatable: true, resizable: true },

  // Colección "Iluminación, energía y servicios técnicos" — señalética y
  // orientación isométrica, se suma a los SVG planos de arriba.
  { id: "iso-totem-direccional-multipanel", nombre: "Tótem direccional multipanel", categoria: "senalizacion", icono: "/symbols/Iluminación, energía y servicios técnicos/01_totem_direccional_multipanel.png", prefijo: "SI", defaultWidth: 1, defaultHeight: 1, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-poste-direccional-madera", nombre: "Poste direccional de madera", categoria: "senalizacion", icono: "/symbols/Iluminación, energía y servicios técnicos/02_poste_direccional_madera.png", prefijo: "SI", defaultWidth: 0.8, defaultHeight: 0.8, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-balizas-peatonales", nombre: "Balizas peatonales", categoria: "senalizacion", icono: "/symbols/Iluminación, energía y servicios técnicos/03_balizas_peatonales.png", prefijo: "SI", defaultWidth: 1, defaultHeight: 1, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-panel-mapa-predio", nombre: "Panel con mapa del predio", categoria: "senalizacion", icono: "/symbols/Iluminación, energía y servicios técnicos/03_panel_mapa_predio.png", prefijo: "SI", defaultWidth: 1.5, defaultHeight: 0.4, unit: "m", rotatable: true, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-marcador-sector-a", nombre: "Marcador de sector A", categoria: "senalizacion", icono: "/symbols/Iluminación, energía y servicios técnicos/04_marcador_sector_a.png", prefijo: "SI", defaultWidth: 0.5, defaultHeight: 0.5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-senal-estacionamiento", nombre: "Señal de estacionamiento", categoria: "senalizacion", icono: "/symbols/Iluminación, energía y servicios técnicos/05_senal_estacionamiento.png", prefijo: "SI", defaultWidth: 0.6, defaultHeight: 0.6, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-senal-estacionamiento-accesible", nombre: "Señal de estacionamiento accesible", categoria: "senalizacion", icono: "/symbols/Iluminación, energía y servicios técnicos/06_estacionamiento_accesible.png", prefijo: "SI", defaultWidth: 0.6, defaultHeight: 0.6, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-poste-direccional-evento", nombre: "Poste direccional de evento", categoria: "senalizacion", icono: "/symbols/Iluminación, energía y servicios técnicos/06_poste_direccional_evento.png", prefijo: "SI", defaultWidth: 0.8, defaultHeight: 0.8, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-senal-accesibilidad", nombre: "Señal de accesibilidad", categoria: "senalizacion", icono: "/symbols/Iluminación, energía y servicios técnicos/07_senal_accesibilidad.png", prefijo: "SI", defaultWidth: 0.6, defaultHeight: 0.6, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-senal-informacion", nombre: "Señal de información", categoria: "senalizacion", icono: "/symbols/Iluminación, energía y servicios técnicos/07_senal_informacion.png", prefijo: "SI", defaultWidth: 0.6, defaultHeight: 0.6, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-senal-sanitarios", nombre: "Señal de sanitarios", categoria: "senalizacion", icono: "/symbols/Iluminación, energía y servicios técnicos/08_senal_sanitarios.png", prefijo: "SI", defaultWidth: 0.6, defaultHeight: 0.6, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-prohibido-ingresar", nombre: "Prohibido ingresar", categoria: "senalizacion", icono: "/symbols/Iluminación, energía y servicios técnicos/12_prohibido_ingresar.png", prefijo: "SI", defaultWidth: 0.6, defaultHeight: 0.6, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-cruce-peatonal", nombre: "Cruce peatonal", categoria: "senalizacion", icono: "/symbols/Iluminación, energía y servicios técnicos/13_cruce_peatonal.png", prefijo: "SI", defaultWidth: 0.6, defaultHeight: 0.6, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-panel-programacion-vacio", nombre: "Panel de programación vacío", categoria: "senalizacion", icono: "/symbols/Iluminación, energía y servicios técnicos/14_panel_programacion_vacio.png", prefijo: "SI", defaultWidth: 1.5, defaultHeight: 0.4, unit: "m", rotatable: true, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-marcador-stand-12", nombre: "Marcador de stand 12", categoria: "senalizacion", icono: "/symbols/Iluminación, energía y servicios técnicos/15_marcador_stand_12.png", prefijo: "SI", defaultWidth: 0.5, defaultHeight: 0.5, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },

  // Colección "circulación y orientación" — cartelería y orientación
  // isométrica, se suma a los SVG planos de arriba.
  { id: "iso-cartel-direccional", nombre: "Cartel direccional", categoria: "senalizacion", icono: "/symbols/circulación y orientación/Cartel direccional.png", prefijo: "SI", defaultWidth: 0.8, defaultHeight: 0.8, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-flechas-circulacion", nombre: "Flechas de circulación", categoria: "senalizacion", icono: "/symbols/circulación y orientación/Flechas de circulación.png", prefijo: "SI", defaultWidth: 1, defaultHeight: 1, unit: "m", rotatable: true, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-plano-general-predio", nombre: "Plano general del predio", categoria: "senalizacion", icono: "/symbols/circulación y orientación/Plano general del predio.png", prefijo: "SI", defaultWidth: 1.5, defaultHeight: 0.4, unit: "m", rotatable: true, resizable: true, estiloIcono: "isometrico" },
  { id: "iso-totem-usted-esta-aqui", nombre: "Tótem \"Usted está aquí\"", categoria: "senalizacion", icono: "/symbols/circulación y orientación/Tótem Usted está aquí.png", prefijo: "SI", defaultWidth: 1, defaultHeight: 1, unit: "m", rotatable: false, resizable: true, estiloIcono: "isometrico" },
];
